In [1]:
import importlib
import sys
import torch

sys.path.insert(0, '..')
sys.path.insert(0, '../..')
sys.path.insert(0, '../../..')

In [2]:
!ls ../../../../encoded_data_v2/helpdesk_all_5_test.pkl
!ls ../../../../encoded_data_v1/helpdesk_all_5_test.pkl

../../../../encoded_data_v2/helpdesk_all_5_test.pkl
../../../../encoded_data_v1/helpdesk_all_5_test.pkl


In [3]:
# Path to your pickle file (saved with torch.save)
# file_path_train = '../../../../encoded_data_v2/helpdesk_all_5_train.pkl'
# helpdesk_train_v2 = torch.load(file_path_train, weights_only=False)

# Path to your pickle file (saved with torch.save)
file_path_train = '../../../../encoded_data_v1/helpdesk_all_5_train.pkl'
helpdesk_train_v1 = torch.load(file_path_train, weights_only=False)


In [17]:
helpdesk_train_v1.tensor_list[0][0][0:10]


tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11,  2,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11,  2,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11,  2,  5,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11,  2,  5,  5,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11,  2,  5,  5,  5,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13,  9, 11,  2],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13,  9, 11,  2,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13,  9, 11,  2,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13,  9, 11,  2,  5,  5,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13,  9, 11,  2,  5,  5,  5,  5]])

In [18]:
helpdesk_train_v1.tensor_list[2][0:10]

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]))