In [1]:
import importlib
import sys
import torch
import numpy as np

sys.path.insert(0, '..')
sys.path.insert(0, '../..')
sys.path.insert(0, '../../..')

In [2]:
import event_log_loader.new_event_log_loader
importlib.reload(event_log_loader.new_event_log_loader)
from event_log_loader.new_event_log_loader import EventLogLoader

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

np.random.seed(17)

event_log_location = '../../../../data/pcr_event_log.csv'

result_name = 'PCR_all_lognormal'

event_log_properties = {
    'case_name' : 'concept:instance',
    'concept_name' : 'concept:name',
    'timestamp_name' : 'time:timestamp',
    'time_since_case_start_column' : 'case_elapsed_time',
    'time_since_last_event_column' : 'event_elapsed_time',
    'day_in_week_column' : 'day_in_week',
    'seconds_in_day_column' : 'seconds_in_day',
    'min_suffix_size' : 5,
    'train_validation_size' : 0.15,
    'test_validation_size' : 0.2,
    'window_size' : 'auto',
    'categorical_columns' : ['concept:name', 'cpee:lifecycle:transition'],
    'continuous_columns' : ['day_in_week', 'seconds_in_day'],
    'continuous_positive_columns' : ['case_elapsed_time', 'event_elapsed_time']
}

# 1) loads event log
# 2) adds EOS to cases
# 3) normalizes numerical features
# 4) imputes features (replaces n.a. categories with a new class for categorical features and average values for numerical featues)
event_log_loader = EventLogLoader(event_log_location, event_log_properties)

Positive Standardization
min,25%,50%,75%,max: [ 0.          9.0863657   9.32800293  9.32800293 11.45982552]
Mean:  [7.29938]
Std:  [3.8676283]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 6.97561400e-03 3.72957848e-02 6.99581957e+00
 6.99581957e+00]
Mean:  [2.474304]
Std:  [3.2164001]


/home/LordKunkler/.local/share/virtualenvs/PrimePPM-tDGhFIeG/lib/python3.13/site-packages/sklearn/preprocessing/_function_transformer.py:210: UserWarning: The provided functions are not strictly inverse of each other. If you are sure you want to proceed regardless, set 'check_inverse=False'.
  warnings.warn(
/home/LordKunkler/.local/share/virtualenvs/PrimePPM-tDGhFIeG/lib/python3.13/site-packages/sklearn/preprocessing/_function_transformer.py:210: UserWarning: The provided functions are not strictly inverse of each other. If you are sure you want to proceed regardless, set 'check_inverse=False'.
  warnings.warn(


In [3]:
print(event_log_loader.encoder_decoder.window_size)

38


In [4]:
train_dataset = event_log_loader.get_dataset('train')
torch.save(train_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_train.pkl')
print(train_dataset.all_categories)

categorical tensors:   0%|          | 0/2 [00:00<?, ?it/s]

concept:name:   0%|          | 0/4009 [00:00<?, ?it/s]

cpee:lifecycle:transition:   0%|          | 0/4009 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/4009 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/4009 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/4009 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [0.         5.98892951 9.47476482 9.48360538 9.48366833]
Mean:  [7.2070484]
Std:  [3.8062491]
Positive Standardization
min,25%,50%,75%,max: [0.         6.14874697 9.4736042  9.48245716 9.48252487]
Mean:  [7.2336454]
Std:  [3.7746854]
Positive Standardization
min,25%,50%,75%,max: [0.         6.15575552 9.4706049  9.47949457 9.47956276]
Mean:  [7.2328844]
Std:  [3.7732122]
Positive Standardization
min,25%,50%,75%,max: [0.         6.04816628 9.46731567 9.4762187  9.47627258]
Mean:  [7.2134924]
Std:  [3.791728]
Positive Standardization
min,25%,50%,75%,max: [0.         5.69692612 9.46438694 9.47332907 9.47339153]
Mean:  [7.1503296]
Std:  [3.867879]
Positive Standardization
min,25%,50%,75%,max: [0.         5.82313228 9.46369553 9.47265196 9.47271156]
Mean:  [7.1746454]
Std:  [3.8342903]
Positive Standardization
min,25%,50%,75%,max: [0.         5.80519271 9.4628315  9.47178793 9.4718504 ]
Mean:  [7.168315]
Std:  [3.8431232]
Positive Standardizatio

event_elapsed_time:   0%|          | 0/4009 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 3.99202155e-03 1.29162259e-02 6.99581957e+00
 9.47375393e+00]
Mean:  [2.59081]
Std:  [3.355321]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 2.49675591e-03 1.48886126e-02 6.99581957e+00
 9.47218227e+00]
Mean:  [2.6055417]
Std:  [3.3556447]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.98754159e-03 1.88217536e-02 6.99581957e+00
 9.46915817e+00]
Mean:  [2.6084511]
Std:  [3.3534074]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 5.48480661e-03 1.88217536e-02 6.99581957e+00
 9.46616077e+00]
Mean:  [2.5925336]
Std:  [3.3567243]
Positive Standardization
min,25%,50%,75%,max: [1.99800287e-03 3.99152527e-03 1.19285714e-02 6.99581957e+00
 9.46385193e+00]
Mean:  [2.564921]
Std:  [3.3560052]
Positive Standardization
min,25%,50%,75%,max: [1.99800287e-03 5.48480661e-03 2.85930544e-01 6.99581957e+00
 9.46298504e+00]
Mean:  [2.5878718]
Std:  [3.3458633]
Positive Standardization
min,25%,50%,7

In [5]:
test_dataset = event_log_loader.get_dataset('test')
torch.save(test_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_test.pkl')

categorical tensors:   0%|          | 0/2 [00:00<?, ?it/s]

concept:name:   0%|          | 0/1233 [00:00<?, ?it/s]

cpee:lifecycle:transition:   0%|          | 0/1233 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/1233 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/1233 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/1233 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [0.         6.09160399 9.47620201 9.48504496 9.48511028]
Mean:  [7.226386]
Std:  [3.7843106]
Positive Standardization
min,25%,50%,75%,max: [0.         6.18421078 9.46900749 9.47790956 9.47797394]
Mean:  [7.2384152]
Std:  [3.7644699]
Positive Standardization
min,25%,50%,75%,max: [0.         5.83744597 9.46600819 9.47494555 9.47504139]
Mean:  [7.175881]
Std:  [3.8364527]
Positive Standardization
min,25%,50%,75%,max: [0.         5.72698498 9.46125221 9.47024012 9.470294  ]
Mean:  [7.154541]
Std:  [3.858955]
Positive Standardization
min,25%,50%,75%,max: [0.         5.82239342 9.46052551 9.46952009 9.46957207]
Mean:  [7.171004]
Std:  [3.8369596]
Positive Standardization
min,25%,50%,75%,max: [0.         6.07014656 9.44736671 9.45646286 9.4565115 ]
Mean:  [7.206124]
Std:  [3.7827451]
Positive Standardization
min,25%,50%,75%,max: [0.         6.39283752 9.44486141 9.45398474 9.45406914]
Mean:  [7.2644334]
Std:  [3.713895]
Positive Standardization
mi

event_elapsed_time:   0%|          | 0/1233 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.48978157e-03 3.41459781e-01 6.99581957e+00
 9.47494602e+00]
Mean:  [2.6165864]
Std:  [3.343564]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.48978157e-03 2.07825396e-02 6.99581957e+00
 9.46746826e+00]
Mean:  [2.6099524]
Std:  [3.3540728]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.98754159e-03 2.66419314e-02 6.99581957e+00
 9.46527576e+00]
Mean:  [2.5892596]
Std:  [3.3472636]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.48978157e-03 2.22343236e-01 6.99581957e+00
 9.46067810e+00]
Mean:  [2.5740674]
Std:  [3.3503335]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 7.96816964e-03 2.37165261e-02 6.99581957e+00
 9.45981312e+00]
Mean:  [2.5725117]
Std:  [3.3565283]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 4.98754159e-03 1.32781103e-01 6.99581957e+00
 9.44613075e+00]
Mean:  [2.5964265]
Std:  [3.3529768]
Positive Standardization
min,25%,50

In [6]:
val_dataset = event_log_loader.get_dataset('val')
torch.save(val_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_val.pkl')

categorical tensors:   0%|          | 0/2 [00:00<?, ?it/s]

concept:name:   0%|          | 0/924 [00:00<?, ?it/s]

cpee:lifecycle:transition:   0%|          | 0/924 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/924 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/924 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/924 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [0.         6.09601545 9.47203159 9.48090887 9.48096561]
Mean:  [7.223572]
Std:  [3.7848313]
Positive Standardization
min,25%,50%,75%,max: [0.         5.73479867 9.46512318 9.4740653  9.47416592]
Mean:  [7.157355]
Std:  [3.8594155]
Positive Standardization
min,25%,50%,75%,max: [0.         5.72519207 9.45734596 9.46633244 9.4664011 ]
Mean:  [7.1518455]
Std:  [3.8587792]
Positive Standardization
min,25%,50%,75%,max: [0.         5.85210514 9.43567848 9.44488049 9.44496346]
Mean:  [7.163382]
Std:  [3.8225927]
Positive Standardization
min,25%,50%,75%,max: [0.         5.65828085 9.43474293 9.44401932 9.4440527 ]
Mean:  [7.129468]
Std:  [3.8653665]
Positive Standardization
min,25%,50%,75%,max: [0.         6.41966963 9.43408298 9.44337177 9.44340515]
Mean:  [7.2618885]
Std:  [3.709074]
Positive Standardization
min,25%,50%,75%,max: [0.         9.32800293 9.43778181 9.44257021 9.44375134]
Mean:  [7.6649976]
Std:  [3.5258746]
Positive Standardization


event_elapsed_time:   0%|          | 0/924 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 3.49376525e-03 1.58733502e-02 6.99581957e+00
 9.47075844e+00]
Mean:  [2.5962543]
Std:  [3.3584328]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 7.47090648e-03 3.14810723e-01 6.99581957e+00
 9.46454144e+00]
Mean:  [2.5964477]
Std:  [3.3364606]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 2.99550896e-03 1.68571174e-02 6.99581957e+00
 9.45677185e+00]
Mean:  [2.568283]
Std:  [3.3544261]
Positive Standardization
min,25%,50%,75%,max: [1.99800287e-03 4.48978157e-03 1.58733502e-02 6.99581957e+00
 9.43489838e+00]
Mean:  [2.5844746]
Std:  [3.347237]
Positive Standardization
min,25%,50%,75%,max: [1.99800287e-03 5.48480661e-03 1.11541368e-01 6.99581957e+00
 9.43423939e+00]
Mean:  [2.5598664]
Std:  [3.354014]
Positive Standardization
min,25%,50%,75%,max: [9.99500393e-04 5.98009559e-03 4.87901643e-02 6.99581957e+00
 9.43148232e+00]
Mean:  [2.6160212]
Std:  [3.3642793]
Positive Standardization
min,25%,50%,

In [7]:
val_dataset[0]

((tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 9, 5, 8, 5]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 4, 4])),
 (tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000, -1.4710, -1.4710, -1.4710, -1.4710, -1.4710]),
  tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     